name: arowana
description: A lightweight HTTP server framework for Dart.
version: 0.1.0
homepage: https://github.com/arcticfox1919/arowana

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  http_methods: ^1.1.1
  http_parser: ^4.0.2
  mime: ^1.0.4
  logging: ^1.2.0
  stream_channel: ^2.1.2
  web_socket_channel: ^2.4.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
