name: arowana
description: A lightweight HTTP server framework for Dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  shelf: ^1.2.0
  http_methods: ^1.1.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
